### ISSUE TITLE
Using Sterling?

### ISSUE THREAD

**Issue by serras** [s-arash/VSCodeAlloyExtension#3]
I was wondering whether using [Sterling](https://github.com/alloy-js/sterling), a JavaScript-based visualizer for Alloy models, could result in better integration with the editor itself. I was thinking of using the [custom editor API](https://code.visualstudio.com/api/extension-guides/custom-editors) for this matter.

**Comment by s-arash** [comment]
Thanks for the suggestion. Does Sterling accept the model files generated by Alloy?
