### ISSUE TITLE
Update jar for Electrum 2.1

### ISSUE THREAD

**Issue by serras** [s-arash/VSCodeAlloyExtension#4]
According to the [official Discourse](https://alloytools.discourse.group/t/new-electrum-release-candidate-towards-alloy-6/87), Electrum (the extension of Alloy with temporal logic) is going to become the next Alloy. Right now it builds upon Alloy 5.1.

I have been working on rebasing your awesome work over that version, leading to [this branch](https://github.com/serras/Electrum2), and it almost works. It would be great to know if you would be OK with releasing a new version of the extension with Electrum 2.1 bundled, since it supersedes the Alloy bundled right now. If not, my plan would be to create a fork of the extension under a new name, if that it OK with you.

Thanks in advance!

**Comment by s-arash** [comment]
I am very much be open to upgrading to Electrum. You say it almost works, where are the areas where it falls short? And how can I help with shoring up the support for Electrum?

**Comment by serras** [comment]
There were some problems when showing models, which I've finally figured out as of https://github.com/serras/Electrum2/commit/8822dc3e1771aaf160ea68616d6fcfaa3b8ab6db. So everything should be ready to go now.

The build works exactly as you did with the regular Alloy: you just need to build the [`ls` branch in my repo](https://github.com/serras/Electrum2) to obtain the jar and put it in the extension directory. How to package or publish the extension is something I don't know how to do, though.

There are a couple of questions still laying around:
- When I try to build the extension locally, I get some errors, even though the extension seems to work fine. This might be due to some updates to VSCode itself, so maybe it's worth looking at those before publishing a new version.
- The actual Electrum2 has this [`copyFromJar`](https://github.com/serras/Electrum2/blob/ls/org.alloytools.alloy.application/src/main/java/edu/mit/csail/sdg/alloy4whole/SimpleGUI.java#L449) being called at initialisation time. I think it also has to be done in our case (but only the "important" files, not the examples), but I don't know exactly where.

**Comment by s-arash** [comment]
It looks like Alloy6/Electrum2 will not be fully backwards compatible with Alloy 5. I'm willing to add support for Alloy6 soon, under a flag or something. My current thinking is to bundle both Alloy5 and Alloy6 jars with the extension and let the user choose which version they want to use.

Another issue I saw is that it looks like some tests fail in your repo (1337 tests completed, 116 failed). Are you seeing the same failed tests?

And finally, are you willing to make a pull request in my Alloy/LS repo with your changes?

Thanks for your great work BTW.

**Comment by serras** [comment]
I agree, giving the user the option seems like the best idea. About the tests, most of them seem to be time-outs, which I cannot faithfully reproduce in my machine (there only 1 times out).

I am not sure whether I can make a pull request, since I rebased the changes over the Electrum2 repo. I think the best option is to create a whole new branch in your repo and pull those changes in. Then we can make PRs to any of the branches, when required.

**Comment by serras** [comment]
Closing since #8 supersedes this issue.
