### ISSUE TITLE
Update jar to Allow 6

### ISSUE THREAD

**Issue by serras** [s-arash/VSCodeAlloyExtension#8]
I've taken some time to update the `alloy6-ls` branch of my [repo](https://github.com/serras/Electrum2) after the point you've left it in your fork. It's now exactly at Alloy 6.0 release.

Would you be open to publishing a new version of this extension with the updated Jar? As far as I know, this version *is* backwards-compatible, which was the main problem found previously at #4.

**Comment by s-arash** [comment]
Absolutely, thanks for your work! It may take me a few days, as I'm racing against a deadline right now.

**Comment by serras** [comment]
No problem at all! Lots of energy for you until your deadline, and let me know if I can help with this in any other way.

**Comment by s-arash** [comment]
The new version of the extension updated to Alloy 6 is published.
